name: Update README 1-5 times every day 🤪

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'   # Runs at midnight
    - cron: '0 6 * * *'   # Runs at 6 AM
    - cron: '0 12 * * *'  # Runs at noon
    - cron: '0 18 * * *'  # Runs at 6 PM
    - cron: '0 23 * * *'  # Runs at 11 PM

jobs:
  update-readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run randomly
        run: |
          RANDOM_NUMBER=$((RANDOM % 5 + 1))

          # Decide whether to run the job based on the random number
          if [ $RANDOM_NUMBER -le 3 ]; then
            echo "Updating README.md file..."
            node index.js > README.md
          else
            echo "Skipping the update of README.md file..."
          fi
        env:
          CI: true
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: camilledtr
          author_email: camilledr10@gmail.com
          force: false
          signoff: false
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
